### ISSUE TITLE
There are some warnings in Flutter 3.0.0 package

### ISSUE THREAD

**Issue by HuseynHuseyni** [imaNNeoFighT/fl_chart#1012]
![image](https://user-images.githubusercontent.com/72157364/168426128-f861ee37-0f35-4a10-8609-becfe2b19a8b.png)

```

/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/fl_chart-0.50.1/lib/src/chart/pie_chart/pie_chart.dart:42:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addPostFrameCallback((_) {
                   ^

/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/fl_chart-0.50.1/lib/src/chart/pie_chart/pie_chart.dart:42:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addPostFrameCallback((_) {
                   ^
```

**Comment by HuseynHuseyni** [comment]
A similar warning :

**Comment by swat199538** [comment]
similar warning
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.3.1 21E258 darwin-x64, locale en)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.0)

Performing hot restart...
Syncing files to device iPhone 13...
../../../Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fl_chart-0.50.5/lib/src/chart/pie_chart/pie_chart.dart:42:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Documents/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addPostFrameCallback((_) {
                            ^^^^^^^^^^^^^^^^^^^^
Restarted application in 745ms.

**Comment by Balvinder471** [comment]
![fl_chart](https://user-images.githubusercontent.com/64981874/168439473-faf18f09-a5bc-4518-ad40-6e45cac37d6d.png)


I am using flutter version 2.16.2 and in my case it is crashing the app and is not just a warning,
seems like a problem with the null safety feature

**Comment by imaNNeoFighT** [comment]
You should upgrade your flutter version to 3.0 (Or stay with the previous version)

**Comment by HuseynHuseyni** [comment]
سلام ايمان جان من نسخه فلاتر ام رو كه بردم روي 3 اين وارنينگ ها رو بهم نشون ميده قبلش مشكلي نبود الان هم روي نسخه 3.0.0 فلاتر هستم.
