### ISSUE TITLE
'axisTitleData' not defined when using LineChartData

### ISSUE THREAD

**Issue by kaarens93** [imaNNeoFighT/fl_chart#151]
Hi, here is my code. 'axisTitleData' not defined as well as 'FlAxisTitleData' and 'AxisTitle'.

```
  LineChartData sampleData1() {
    return LineChartData(
      
      gridData: const FlGridData(
        show: false,
      ),
      axisTitleData: FlAxisTitleData(
          leftTitle:
              AxisTitle(showTitle: true, titleText: 'Return', margin: 4)),
```

**Comment by imaNNeoFighT** [comment]
Hi,
which version are you using?

**Comment by kaarens93** [comment]
I am using 0.6.0. I changed to 0.6.2 and it works perfectly now. So silly that I did not check before. Thank you!

**Comment by imaNNeoFighT** [comment]
No problem.
Cheers!

**Comment by pvaibhav** [comment]
Reopening this issue because I just updated to v0.55.0 which was using 0.36.3 earlier, and now `LineChartData` doesn't have an `axisTitleData:` named parameter anymore. The documentation still refers to it, including the source code file's documentation comments. But the parameter has been removed, it seems in this commit: https://github.com/imaNNeoFighT/fl_chart/commit/43fe43aae5d686da476c0f86bf7f2be37cd4edd5

Can you please document what we need to do to adapt? Thanks.
