### ISSUE TITLE
support custom widget for titles

### ISSUE THREAD

**Issue by yoonst** [imaNNeoFighT/fl_chart#183]
support custom widget for titles by returning Widget in `getTitles`

Maybe we can use `WidgetSpan` in place of `TextSpan`.
https://api.flutter.dev/flutter/painting/InlineSpan-class.html

## old:
```dart
getTitles: (double value) {
  return value.toString();
},
```

## new:
```dart
getTitles: (double value) {
  return Text(value.toString());
},
```

**Comment by vintage** [comment]
@imaNNeoFighT Is there any known workaround on how to display custom widget or at least image as title? I've got a chart which display mood changes over time and the titles are not text-based unfortunately - these are custom widgets, but could workaround it with some dummy images if that's somehow possible.

**Comment by imaNNeoFighT** [comment]
We don't have any built-in solution for this,
but we are trying to find a proper way to do that.

**Comment by imaNNeoFighT** [comment]
Some samples from #215:

<img src="https://user-images.githubusercontent.com/5210467/75750253-6453b700-5d56-11ea-8f89-3762508759d0.png" width=337 />

<img src="https://user-images.githubusercontent.com/5210467/76693285-12375d80-6695-11ea-9dfa-0a0f7d48f815.png" width=337 />

<img src="https://user-images.githubusercontent.com/5210467/76693286-15324e00-6695-11ea-808c-a2364bc330b2.png" width=337 />

**Comment by imaNNeoFighT** [comment]
Heeey guys. What's up?
We have an important update in [0.50.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.50.0).
At this time, we support `widgets` as titles instead of a boring string.
Don't forget to check out the [migration guide](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/migration_guides/MIGRATION_00_50_00.md). Because there are some breaking changes.

I tried to implement two samples. check them out:

**LineSample8:**
<img width="400" alt="line_chart_sample_8" src="https://user-images.githubusercontent.com/7009300/159998916-f5ec2f77-0c15-4de4-ab20-22835025e34a.png">

**BarSample7:**
<img width="400" src="https://user-images.githubusercontent.com/7009300/159999037-cfc85a43-2146-417c-a80e-14eea62e5c33.gif" />
