### ISSUE TITLE
how to handle normal taps on a pie section with touchCallback 

### ISSUE THREAD

**Issue by Sarathlal13** [imaNNeoFighT/fl_chart#210]
FlLongPressStart, FlLongPressMoveUpdate, FlLongPressEnd, FlPanStart, FlPanMoveUpdate, FlPanEnd with these touch behaviors how can i trigger a normal button tap on a pie section. i want to navigate to  a new page on tap

**Comment by imaNNeoFighT** [comment]
Hi, great question, unfortunately, we didn't support it built-in (due to some complexity).
but there is a sample that we've implemented onTap behavior,
check it out:
##### Sample 2 ([Source Code](/example/lib/scatter_chart/samples/scatter_chart_sample2.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/scatter_chart/scatter_chart_sample_2.gif" width="300" >

**Comment by imaNNeoFighT** [comment]
But let it be open, we will handle it built-in ASAP.
Stay tuned, thank yout!

**Comment by Sarathlal13** [comment]
thanks bro!

**Comment by imaNNeoFighT** [comment]
You're welcome ;)

**Comment by imaNNeoFighT** [comment]
We have just added `clickHappened` property in the touch responses.
check it out in [0.30.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.30.0)

We used this property in:

##### Scatter Sample 2 ([Source Code](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/scatter_chart/samples/scatter_chart_sample2.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/scatter_chart/scatter_chart_sample_2.gif" width="300" >
