### ISSUE TITLE
Tapping a dot doesn't work when there are multiple dots with the same X value

### ISSUE THREAD

**Issue by tudor07** [imaNNeoFighT/fl_chart#261]
I found another bug. When you have multiple values with the same X value but different Y values, the detection mechanism does not work, you can select only one dot.
Example:
![example](https://camo.githubusercontent.com/dff3d5d5e89e8212d812bb5bf5bec671fc6ebe3d/68747470733a2f2f692e696d6775722e636f6d2f4c35584f6442342e706e67)
In this case only 4.10% can be chosen.

**Comment by imaNNeoFighT** [comment]
Could you please provide a reproducible code to show the bug?
because in Sample 1, we have some points on the same x-axis, and touch is working correctly.

##### Sample 1 ([Source Code](/example/lib/line_chart/samples/line_chart_sample1.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_1.gif" width="300" >

**Comment by tudor07** [comment]
@imaNNeoFighT in that sample you highlight all the dots, what if you want to highlight only one?

**Comment by imaNNeoFighT** [comment]
Got it

**Comment by adiltirur** [comment]
+1

**Comment by imaNNeoFighT** [comment]
In [0.45.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.45.0) you can customize `distanceCalculator` property in our [LineTouchData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linetouchdata-read-about-touch-handling). 
Also, you have access to these distances on [TouchLineBarSpot](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#TouchLineBarSpot) which exists in [LineTouchResponse](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linetouchresponse).

Thanks to @joeldomke
