### ISSUE TITLE
pie is not work in web ,But it is ok on mobile

### ISSUE THREAD

**Issue by YQYOnTheRoad** [imaNNeoFighT/fl_chart#277]
this is on mobile
![device-2020-04-01-190605](https://user-images.githubusercontent.com/19703102/78130640-41e3b500-744c-11ea-82f6-143b75c7d3e7.png)

this is on web
![image](https://user-images.githubusercontent.com/19703102/78130894-b3bbfe80-744c-11ea-9065-bf5a585ebc2a.png)

I found this way in #95 
flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true --release

it's work ,but...
![image](https://user-images.githubusercontent.com/19703102/78131548-d69ae280-744d-11ea-8a43-9ceb19831e21.png)

all chinese garbled

so how can i fix this problem,if you konw something about this 
tell me pls, thans a lot

**Comment by alexodus** [comment]
+1

**Comment by frmunozr10** [comment]
+1

**Comment by Pitazzo** [comment]
Exactly same problem here

**Comment by matthewrice345** [comment]
+1

**Comment by surveshoeb** [comment]
Any update on this issue?

**Comment by alfinbi** [comment]
+1

**Comment by imaNNeoFighT** [comment]
Flutter has some problems with BlendMode on the web [1](https://github.com/flutter/flutter/issues/560710), [2](https://github.com/flutter/flutter/issues/29483),....
And FL Chart uses `BlendMode.dstIn` for clearing sectionsSpace, that's why you see a blank screen instead of a PieChart,
I decided to ignore [PieChartData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/pie_chart.md#piechartdata).`sectionsSpace` if you are running on the web.
BTW, I'm happy to say that you can run it on the web without `--dart-define=FLUTTER_WEB_USE_SKIA=true`, in the [0.9.4](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.9.4) version.
Thanks for letting me know, and for sure thank you for your patience!

**Comment by imaNNeoFighT** [comment]
Please try to run it and approve that it's working to close this issue.
Thanks!

**Comment by YQYOnTheRoad** [comment]
> Flutter has some problems with BlendMode on the web [1](https://github.com/flutter/flutter/issues/560710), [2](https://github.com/flutter/flutter/issues/29483),....
> And FL Chart uses `BlendMode.dstIn` for clearing sectionsSpace, that's why you see a blank screen instead of a PieChart,
> I decided to ignore [PieChartData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/pie_chart.md#piechartdata).`sectionsSpace` if you are running on the web.
> BTW, I'm happy to say that you can run it on the web without `--dart-define=FLUTTER_WEB_USE_SKIA=true`, in the [0.9.4](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.9.4) version.
> Thanks for letting me know, and for sure thank you for your patience!

Oh！I tried it in 0.9.4 version.
pie is work on the web！！！
Thanks for your hard work
