### ISSUE TITLE
Linechart not displaying Chart when data is updated via Proivder listener

### ISSUE THREAD

**Issue by kdhanji87** [imaNNeoFighT/fl_chart#288]
plugin

the datasource for the linechart is uisng a provider that is listening for changes, i also have a Date filter that calls an api and gets the data for that date range and refreshes the data

what i am finding is when i refresh the data for a diffrent date range, i can see the data is being sent to the widget but the line chart is not rendering/rebuilt, if i switch back to the default date range the first loaded chart is displayed correctly.

example, month APRIL is inital Date Range that is built

![image](https://user-images.githubusercontent.com/9853548/78460830-565bd200-7718-11ea-98a3-c322c4efb370.png)

when i change the Date Range to March, 

![image](https://user-images.githubusercontent.com/9853548/78460839-7390a080-7718-11ea-8cdc-4080c41c7ef6.png)

the linechart dosnt update with the new data, i can see the data has has the list of updated FL Spots when the data range has been changed, but the widget is not redrawing the line

i saw that an #16 was suppose to resolve this issue but i maybe doing something wrong

**Comment by imaNNeoFighT** [comment]
Hi @kdhanji87.
The best way and fastest way to fix this is a reproducible code.
Reproducible code is a code contains the `main()` function and anything needed to run independently and represents the bug,
your code is not a reproducible code based on my definition, and I can't read it line by line, because as you see there are more than 40 issues, that I don't have enough time to read the codes line by line.
please help me by providing me a reproducible code, that I copy-paste it to my main class and it runs independently.
Thanks for understanding!

**Comment by kdhanji87** [comment]
Update,

managed to figure it out, turns out the issue was with the minX and MaxX
