### ISSUE TITLE
Request and question  :How I get a dot value ?

### ISSUE THREAD

**Issue by redhotsixbull** [imaNNeoFighT/fl_chart#411]
Hi :>

thank u for u r package

I want a make that tap in dot in linegraph. popup or display on graph dot value.

I know that touchTooltip is hilight event. So hand out of app can't display correctly value.

I want a click event at dot in linegraph. not hover or hilight 

I'm sorry that I'm not good at English

If u can't understand Leave a message
  
 

** Don't make a duplicate issue.
You can search in issues to make sure there isn't any already opened issue with your concern.

**Is your feature request relasted to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by imaNNeoFighT** [comment]
Hi,
Are you looking for something like this example?
(Click to show a tooltip, instead of move touch on them)


##### Sample 2 ([Source Code](/example/lib/scatter_chart/samples/scatter_chart_sample2.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/scatter_chart/scatter_chart_sample_2.gif" width="300" >
