### ISSUE TITLE
Bug: Round Bars Rendering Invalid (when differences are too high?)

### ISSUE THREAD

**Issue by sofakingforever** [imaNNeoFighT/fl_chart#43]
As seen in the screenshots below, when using rounded bars, and having the difference between the bars - we get this weird behavior.

When the Y values are something like 0,0,3,4 - **everything is ok**.
When the Y values are something like 0,0,30,1750 - **the last bar is cut at the bottom**.

(the longer one doesn't reach the real widget bottom or the shorter one overreaches. not sure.)

**When turning off the rounded corners - the bars seem fine.**

I tried debugging it for a bit but didn't really understand what's going on.
Let me know if there's anything else I can help you with.

![Screenshot_20190711-003649](https://user-images.githubusercontent.com/27860259/61006975-5e970480-a374-11e9-9e0b-503d99efe4f7.png)
![Screenshot_20190711-003700](https://user-images.githubusercontent.com/27860259/61006976-5e970480-a374-11e9-9637-94b0dfa1e11f.png)

**Comment by sofakingforever** [comment]
This one is from generating random numbers between 0-100 for all the bars

![Screenshot_20190711-005241](https://user-images.githubusercontent.com/27860259/61007762-5d66d700-a376-11e9-8a3c-2b9cc1f97c50.png)

**Comment by imaNNeoFighT** [comment]
Hi, this problem happens only when you set rounded corners ON, I supposed to reduce the width of the bars that their height is lower than their height (also it didn't works currently because codes were unused),
Bytheway, I decided to change the solution and now we show the bars that have low y (height) values with the height that is the same as with.
determine when you have a bar with 0.5 value and another one with 100,
we show the 0.5 bar with the minimum possible height, that is the width of them (because we show them as round lines, the minimum height is the with (such a circle) because we don't want to show ellipse).
Resolved in [0.1.4](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.1.4).
Thanks for contributing, Cheers!

**Comment by sofakingforever** [comment]
Amazing! Works perfectly now 😁

**Comment by imaNNeoFighT** [comment]
Thank you, your samples is amazing, 
If it possible share it here with correct representatiom, 
And maybe we have catalog in future, then I can add samples there.

**Comment by sofakingforever** [comment]
Sure!

![Screenshot_20190711-235813](https://user-images.githubusercontent.com/27860259/61084999-e265f500-a437-11e9-85cf-9ddba0432ac5.png)

**Comment by imaNNeoFighT** [comment]
your samples are beautiful, 
If you can, make a PR and add one of them in the BarChart samples.
