### ISSUE TITLE
Ability to align text labels for charts

### ISSUE THREAD

**Issue by ToyWalrus** [imaNNeoFighT/fl_chart#784]
I'll start out by saying that this issue has already been asked for but no real resolution was made before it was closed, so I thought I'd reopen a new issue for it.  https://github.com/imaNNeoFighT/fl_chart/issues/35

The issue I'm facing is that there's no way currently to control the `textAlign` property in the charts. This seems like it would be a simple fix by adding an additional parameter to the `SideTitles` class, either a function like `getTextAlignment()` (like is happening with the `getTextStyles()` function) or just a flat `textAlign` for all the labels. If you'd like me to make a PR with the fix then let me know -- however I'm new and inexperienced when it comes to contributing to open source projects.

As far as practical applications go, I took an example screenshot from my app. As you can see in this image, because there's no way to right-align the text, the labels appear misaligned with one another. I've also had the desire to realign labels on the x-axis of a line chart but, again, was unable to do so.
<img width="822" alt="Screen Shot 2021-10-01 at 3 54 39 PM" src="https://user-images.githubusercontent.com/25328178/135690256-d98d183e-ae7c-4daa-84ed-b702add0ace7.png">

**Comment by imaNNeoFighT** [comment]
Now there is a `textAlign` property in [SideTitles](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/base_chart.md#sidetitles).
Please check it out in [0.41.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.41.0)!

**Comment by DevDu** [comment]
> Now there is a `textAlign` property in [SideTitles](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/base_chart.md#sidetitles).
> Please check it out in [0.41.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.41.0)!

i can't found it

**Comment by imaNNeoFighT** [comment]
Sorry I sent you the wrong link.
So we have a new release today with a lot of changes.
From now, you can pass a widget as a title (instead of a boring string).
Please check our release note here in [0.50.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.50.0).


Also here is the [migration guide](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/migration_guides/MIGRATION_00_50_00.md).

**LineChartSample 8** ([Source Code](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/line_chart/samples/line_chart_sample8.dart))

<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_8.png" width="300" >

**BarChartSample 7** ([Source Code](https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/bar_chart/samples/bar_chart_sample7.dart))

<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_7.gif" width="300" >
