### ISSUE TITLE
BarAreaData does not exist. Grid lines inverted property name

### ISSUE THREAD

**Issue by javiermrz** [imaNNeoFighT/fl_chart#85]
Hey! First of all, thanks for this great library, I was searching like crazy through internet and only found charts_flutter, and then last week I accidentally came across this one and it's so beautiful, nice work :)

Anyway, I was implementing the Line Chart with one of your examples given
(https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/line_chart/samples/line_chart_sample2.dart) 
and there was an error that said that **BarAreaData** does not exist (in property `belowBarData`). I looked at the kind of data that the property expected to receive and it was `BelowBarData` (sounds logic). I don't know if it's a mistake in the docs or just a miss, but just saying so you can change it and future devs don't come across the same.

Also, there is another issue that I'll also say here for not issuing two times. In the class `FlGridData`, there are two properties: `getDrawingVerticalGridLine` and `getDrawingHorizontalGridLine`. I don't know if it was intended, but the **getDrawingVerticalGridLine** modifies the **horizontal** lines and the other way around, which is kind of weird. Is this the correct way? :/

However, these are little things in case I can help improve a bit this amazing library. Thanks again for it! :)

**Comment by javiermrz** [comment]
> methods

properties

**Comment by imaNNeoFighT** [comment]
Hi there,
1. which version of fl_chart did you use? give me some hints to reproduce it, I don't know how did you get this error.
2. I know its weird somehow, but I made it intentionally because we have some titles in the left or bottom of the chart, earlier we had to call them "VerticalTitles" (for left titles) and "HorizontalTitles" (for bottom titles), then I decided to name the lines that end to vertical titles, "VerticalLines", and also the lines that end in horizontal titles, "HorizontalLines,
and now there are no horizontal and vertical titles, then we can change it to be clear, and you're right, I will change it.
I'm really glad to get these issues, absolutely it is a contribution and it makes the library better and better.
Thanks

**Comment by javiermrz** [comment]
I'm using fl_chart: ^0.2.0. 
To reproduce it, I just made a Widget Class, and copied the exact code that is in here: 
https://github.com/imaNNeoFighT/fl_chart/blob/master/example/lib/line_chart/samples/line_chart_sample2.dart

Then called the Widget from main.dart.

**Comment by imaNNeoFighT** [comment]
As you know the samples implemented in the latest version.
You have to update your fl_chart, at the moment the latest one is [0.3.3](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.3.3).

**Comment by imaNNeoFighT** [comment]
Horizontal And Vertical semantics in [FlGridData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/base_chart.md#FlGridData) has corrected in [0.3.4](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.3.4),
Thank you so much.
