### ISSUE TITLE
Detect touch on dots on chart

### ISSUE THREAD

**Issue by abinmittu** [imaNNeoFighT/fl_chart#993]
Is there a way to detect touch on dots representing data points on line chart. I am searching for something like an ```onTap``` for dots. Since dots are shown by ```FlDotCirclePainter```, I cannot wrap it in a Gesture detector.

**Comment by agoldm** [comment]
You can use LineChart->LineChartData->LineTouchData->touchCallback witch is a void function having the current event happening such as `FlPanStartEvent` or `FlPanUpdateEvent` and etc, and having the `touchResponse` with has lineChartSpots. If lineChartSpots is null the touch is on the graph but not on one of your spots. otherwise, you can have the spotted x/y by: `touchResponse.lineBarSpots![0].x` or `touchResponse.lineBarSpots![0].y`.
Hope I helped:)

**Comment by agoldm** [comment]
@abinmittu
